apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ixlg8gobn-nodejs-gitops
  description: This is GitOps manifest for ixlg8gobn-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ixlg8gobn-nodejs
    backstage.io/kubernetes-id: ixlg8gobn-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ixlg8gobn-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ixlg8gobn-nodejs
