apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ixlg8gobn-nodejs
  janus-idp.io/tekton: ixlg8gobn-nodejs
  backstage.io/kubernetes-id: ixlg8gobn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ixlg8gobn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
